blank_issues_enabled: false  # ç¦æ­¢ç©ºç™½ Issueï¼Œå¼ºåˆ¶ä½¿ç”¨æ¨¡æ¿

contact_links:
  - name: ğŸ“š å®˜æ–¹æ–‡æ¡£
    url: https://ais-bench-benchmark-rf.readthedocs.io/zh-cn/latest/
    about: é‡åˆ°é—®é¢˜è¯·åœ¨å®˜æ–¹æ–‡æ¡£ä¸­æœç´¢ã€‚
  - name: ğŸ“š Documentation
    url: https://ais-bench-benchmark-rf.readthedocs.io/en/latest/
    about: Check if your question is answered in the documentation.
